# prints gerais by Daniel

print("TIME VARIABLES:")
print("---------------------------------")
print("t0 = {:0.3f} s".format(t0))
print("tF = {:0.3f} s".format(tf))
print("dT = {:0.3f} s".format(dt))
print("=================================")
print("VELOCITIES:")
print("Initial:")
print("v0 = {:0.4f} m/s".format(v0))
print("=================================")
print("POSITIONS:")
print("Initial:")
print("x0 = {:0.4f} m".format(x0))
print("---------------------------------")
print("=================================")
print("WAVE RELATED:")
print("A = {:0.4f} m".format(A))
print("---------------------------------")